<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Project;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository {

    public function getAll() {
        return $this->findBy(['deletedAt' => null]);
    }

    public function getByProject(Project $project) {
        return $this->createQueryBuilder('c')
            ->join('c.projects', 'p')
            ->where('p.id = :project')
            ->setParameter('project', $project)
            ->getQuery()
            ->getResult();
    }

}
