<?php

namespace AppBundle\Repository;


/**
 * ClientUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientUserRepository extends \Doctrine\ORM\EntityRepository {

}
