<?php

namespace AppBundle\Repository;


/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository {

    public function getAll() {
        return $this->createQueryBuilder('p')
            ->join('p.client', 'c')
            ->where('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->getQuery()
            ->getResult();
    }

}
