<?php

namespace AppBundle\Repository;


/**
 * TaskNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskNoteRepository extends \Doctrine\ORM\EntityRepository {

}
