<?php

namespace AppBundle\Repository;


use AppBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository {

    public function assignedTo($user, $project = null) {
        $query = $this->createQueryBuilder('t')
            ->join('t.assignee', 'a')
            ->where('t.deletedAt is null')
            ->andWhere('a.id = :user')
            ->setParameter('user', $user);

        if(!empty($project)) {
            $query->andWhere('t.project = :project')
                ->setParameter('project', $project);
        }

        return $query->getQuery()->getResult();
    }
}
