<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Client;
use AppBundle\Entity\Project;
use AppBundle\Entity\User;

/**
 * TimeSpentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeSpentRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * @param User      $user
     * @param \DateTime $day
     *
     * @return array
     */
    public function getByDay(User $user, \DateTime $day) {
        return $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('ts.user = :user')
            ->andWhere('ts.date = :day')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->setParameter('user', $user)
            ->setParameter('day', $day)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     *
     * @return array
     * @throws \Exception
     */
    public function getWeekSpent(User $user) {
        $monday = new \DateTime();
        $monday->setTimestamp(strtotime('monday this week'));
        $saturday = new \DateTime();
        $saturday->setTimestamp(strtotime('saturday this week'));

        return $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('ts.user = :user')
            ->andWhere('ts.date >= :start')
            ->andWhere('ts.date <= :end')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->orderBy('ts.date')
            ->setParameter('user', $user)
            ->setParameter('start', $monday)
            ->setParameter('end', $saturday)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     *
     * @return array
     * @throws \Exception
     */
    public function getMonthSpent(User $user) {
        $start = \DateTime::createFromFormat('Ymd', date('Ym01'));
        $end = new \DateTime();
        $end->setTimestamp(strtotime('last day of this month'));

        return $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('ts.user = :user')
            ->andWhere('ts.date >= :start')
            ->andWhere('ts.date <= :end')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->orderBy('ts.date')
            ->setParameter('user', $user)
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     *
     * @return array
     * @throws \Exception
     */
    public function getClientSpent(\DateTime $start, \DateTime $end, Client $client, $user = null) {
        $query = $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('p.client = :client')
            ->andWhere('ts.date >= :start')
            ->andWhere('ts.date <= :end')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->orderBy('ts.date')
            ->setParameter('client', $client)
            ->setParameter('start', $start)
            ->setParameter('end', $end);

        if(!is_null($user)) {
            $query->andWhere('ts.user = :user')
                ->setParameter('user', $user);
        }

        return $query->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     *
     * @return array
     * @throws \Exception
     */
    public function getProjectSpent(\DateTime $start, \DateTime $end, Project $project, $user = null) {
        $query = $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('t.project = :project')
            ->andWhere('ts.date >= :start')
            ->andWhere('ts.date <= :end')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->orderBy('ts.date')
            ->setParameter('project', $project)
            ->setParameter('start', $start)
            ->setParameter('end', $end);

        if(!is_null($user)) {
            $query->andWhere('ts.user = :user')
                ->setParameter('user', $user);
        }

        return $query->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     *
     * @return array
     * @throws \Exception
     */
    public function getUserSpent(\DateTime $start, \DateTime $end, User $user, $project = null) {
         $query = $this->createQueryBuilder('ts')
            ->join('ts.task', 't')
            ->join('t.project', 'p')
            ->join('p.client', 'c')
            ->where('ts.user = :user')
            ->andWhere('ts.date >= :start')
            ->andWhere('ts.date <= :end')
            ->andWhere('t.deletedAt is null')
            ->andWhere('p.deletedAt is null')
            ->andWhere('c.deletedAt is null')
            ->orderBy('ts.date')
            ->setParameter('user', $user)
            ->setParameter('start', $start)
            ->setParameter('end', $end);


        if(!empty($project)) {
            $query->andWhere('t.project = :project')
                ->setParameter('project', $project);
        }

        return $query->getQuery()
            ->getResult();
    }

}
