<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKj3kwgx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKj3kwgx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKj3kwgx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKj3kwgx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKj3kwgx\appProdProjectContainer([
    'container.build_hash' => 'Kj3kwgx',
    'container.build_id' => '5a695dac',
    'container.build_time' => 1747322494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKj3kwgx');
