services:
  app.admin.client:
    class: AppBundle\Admin\ClientAdmin
    arguments: [~, AppBundle\Entity\Client, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Gestionale, label: Clienti }
    public: true

  app.admin.priority:
    class: AppBundle\Admin\PriorityAdmin
    arguments: [~, AppBundle\Entity\Priority, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Configurazione, label: Priorità }
    public: true

  app.admin.project:
    class: AppBundle\Admin\ProjectAdmin
    arguments: [~, AppBundle\Entity\Project, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Gestionale, label: Progetti }
    public: true

  app.admin.task:
    class: AppBundle\Admin\TaskAdmin
    arguments: [~, AppBundle\Entity\Task, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Gestionale, label: Attività }
    public: true

  app.admin.user:
    class: AppBundle\Admin\UserAdmin
    arguments: [~, AppBundle\Entity\User, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Gestionale, label: Utenti }
    public: true
