<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\TaskController:detailAction' => function () {
    return ${($_ = isset($this->services['service_locator.ejqsmoy']) ? $this->services['service_locator.ejqsmoy'] : $this->load('getServiceLocator_EjqsmoyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.ejqsmoy']) ? $this->services['service_locator.ejqsmoy'] : $this->load('getServiceLocator_EjqsmoyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:newAction' => function () {
    return ${($_ = isset($this->services['service_locator.fnls1u1']) ? $this->services['service_locator.fnls1u1'] : $this->load('getServiceLocator_Fnls1u1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.s955kho']) ? $this->services['service_locator.s955kho'] : $this->load('getServiceLocator_S955khoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.s955kho']) ? $this->services['service_locator.s955kho'] : $this->load('getServiceLocator_S955khoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController:newAction' => function () {
    return ${($_ = isset($this->services['service_locator.6ep_fad']) ? $this->services['service_locator.6ep_fad'] : $this->load('getServiceLocator_6epFadService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController:trackTaskTimeAction' => function () {
    return ${($_ = isset($this->services['service_locator.6ep_fad']) ? $this->services['service_locator.6ep_fad'] : $this->load('getServiceLocator_6epFadService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::detailAction' => function () {
    return ${($_ = isset($this->services['service_locator.ejqsmoy']) ? $this->services['service_locator.ejqsmoy'] : $this->load('getServiceLocator_EjqsmoyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.ejqsmoy']) ? $this->services['service_locator.ejqsmoy'] : $this->load('getServiceLocator_EjqsmoyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::newAction' => function () {
    return ${($_ = isset($this->services['service_locator.fnls1u1']) ? $this->services['service_locator.fnls1u1'] : $this->load('getServiceLocator_Fnls1u1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.s955kho']) ? $this->services['service_locator.s955kho'] : $this->load('getServiceLocator_S955khoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.s955kho']) ? $this->services['service_locator.s955kho'] : $this->load('getServiceLocator_S955khoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController::newAction' => function () {
    return ${($_ = isset($this->services['service_locator.6ep_fad']) ? $this->services['service_locator.6ep_fad'] : $this->load('getServiceLocator_6epFadService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TimeController::trackTaskTimeAction' => function () {
    return ${($_ = isset($this->services['service_locator.6ep_fad']) ? $this->services['service_locator.6ep_fad'] : $this->load('getServiceLocator_6epFadService.php')) && false ?: '_'};
}]));
