<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.builder.orm_datagrid' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Builder/BuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Builder/DatagridBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/doctrine-orm-admin-bundle/src/Builder/DatagridBuilder.php';

return $this->services['sonata.admin.builder.orm_datagrid'] = new \Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.builder.filter.factory']) ? $this->services['sonata.admin.builder.filter.factory'] : $this->load('getSonata_Admin_Builder_Filter_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.guesser.orm_datagrid_chain']) ? $this->services['sonata.admin.guesser.orm_datagrid_chain'] : $this->load('getSonata_Admin_Guesser_OrmDatagridChainService.php')) && false ?: '_'}, true);
