<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6ep_fad' shared service.

return $this->services['service_locator.6ep_fad'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['logger' => function () {
    return ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'};
}]);
