<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Utils\Services\UtilsService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Utils/Services/UtilsService.php';

return $this->services['AppBundle\Utils\Services\UtilsService'] = new \AppBundle\Utils\Services\UtilsService();
